spring:
  application:
    name: meli-checkout-api
  validation:
    fail-fast: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized

# resilience4j:
#   circuitbreaker:
#     instances:
#       fraudeService:
#         registerHealthIndicator: true
#         slidingWindowSize: 10
#         failureRateThreshold: 50
#         slowCallRateThreshold: 60
#         slowCallDurationThreshold: 2s
#         waitDurationInOpenState: 30s
#         permittedNumberOfCallsInHalfOpenState: 3
#         minimumNumberOfCalls: 5

checkout:
  fraude:
    simular-falhas: false

springdoc:
 swagger-ui:
   path: /swagger-ui.html
 api-docs:
   path: /v3/api-docs